{% set version = "12.4.1" %}

package:
  name: cuda
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __linux  # [linux]
    - __win    # [win]
    - cuda-runtime {{ version }}
    - cuda-toolkit {{ version }}

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all the available packages for native CUDA development
  description: |
    Meta-package containing all the available packages required for native CUDA
    development
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
    - bdice
    - jakirkham
    - kmittman
    - leofang
    - robertmaynard
    - vyasr
